### ISSUE TITLE
problem downloading chromium with the plugin on windows 10

### ISSUE THREAD

**Issue by amirkibbar** [leontebbens/chromedriver-updater-plugin#1]
Hi,

I tried this plugin on Windows 10 and gradle 2.12, it seems that the plugin attempts to incorrectly construct the URL from which to download chromium. Here's the error log:

```
Downloading Chromedriver 2.21
 from http://chromedriver.storage.googleapis.com ...
:updateChromedriver FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':updateChromedriver'.
> java.net.MalformedURLException: Illegal character in URL
```

I looked into the code and there seem to be 2 problems here:
- in lines 54-56 the usage of File.separator in the construction of the URL is incorrect, in URL it should always be forward slash / here's the corrected code:
```groovy
            downloadAndUnzip(latestDriverBaseUrl + "/chromedriver_mac32.zip", project.buildDir.toString() + File.separator + "mac")
            downloadAndUnzip(latestDriverBaseUrl + "/chromedriver_win32.zip", project.buildDir.toString() + File.separator + "win")
            downloadAndUnzip(latestDriverBaseUrl + "/chromedriver_linux64.zip", project.buildDir.toString() + File.separator + "linux")
```
- in line 86 the version read from the LATEST_RELEASE remote file on the chromium site is not trimmed, so if this file has a new line (like it has now) the result string would be, for example: "2.21\n" - when constructing the URL to fetch chromium from this causes the URL to be malformed because of the 'n in it. Adding .trim() to the version read solves this problem, here's the corrected line:
```groovy
response.success = { resp, reader -> ver = reader.getText().trim()
```

Also I think it would be better not to store the .idea directory in git. I'll try to create a pull request with these fixes.

Thanks,
Amir

**Comment by amirkibbar** [comment]
Hi,

It seems that this plugin is not maintained. 

@leontebbens Would you consider adding me as a contributor so that I could continue to maintain it?

Thanks

**Comment by leontebbens** [comment]
Hi Amir, thanx for your fixes and the Groovy code improvements (this was my first Groovy code). I wrote this plugin a while ago, but was never able to get it working behind my company firewall / proxy, so yeah, it is not really maintained. I added you as contributor :-).

**Comment by amirkibbar** [comment]
@leontebbens I too have an (evil corporate) http proxy, I'll try to get the plugin to work behind it. Thanks for adding me as a contributor

**Comment by amirkibbar** [comment]
I just merged my old pull request to fix the URL and bumped the version to 1.3, can you please publish the version's binaries?

**Comment by leontebbens** [comment]
Hi Amir, done! :-). Let me know if it works.

**Comment by amirkibbar** [comment]
yep, works for me

**Comment by leontebbens** [comment]
Great!
