### ISSUE TITLE
Driver not executable in Mac

### ISSUE THREAD

**Issue by chiquitinxx** [leontebbens/chromedriver-updater-plugin#10]
Hey there! Congratulations on the plugin :)

I'm trying runing chrome tests in a mac, and I get the following error:

java.lang.IllegalStateException: The driver is not executable: ../build/chromedriver/mac/chromedriver
	at com.google.common.base.Preconditions.checkState(Preconditions.java:199)
	at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:125)

If i do chmod +x on the file then it works, but maybe you can do that in the plugin after a release is installed. Thank you.

**Comment by amirkibbar** [comment]
please see pull request #11

**Comment by leontebbens** [comment]
Fast as always @amirkibbar! Thanx for the fix.
