### ISSUE TITLE
Adapt to new chromedriver naming scheme for macOS ARM64 CPUs

### ISSUE THREAD

**Issue by skiedrowski** [leontebbens/chromedriver-updater-plugin#19]
until version 106.0.5249.21 `chromedriver_mac64_m1.zip`
since version 106.0.5249.61 `chromedriver_mac_arm64.zip`

There are more arm64 CPU than only m1, so this seems reasonable.

**Comment by skiedrowski** [comment]
I am working on a pull request

**Comment by leontebbens** [comment]
Released in version 1.8.0. Thanx for the commits @skiedrowski !
