### ISSUE TITLE
Adding downloaded path to system property?

### ISSUE THREAD

**Issue by foragerr** [leontebbens/chromedriver-updater-plugin#3]
Hi, thanks for building this plugin, was looking for something to manage chromedriver binaries.

running `updateChromedriver` fetches the binary and puts it in the `buildDir`, but is there a recommeded way to then set system property `webdriver.chrome.driver` to this path?

**Comment by leontebbens** [comment]
java -Dwebdriver.chrome.driver=/path/to/chromedriver
?

**Comment by foragerr** [comment]
Well, This being a gradle plugin. I was expecting to have a config line in build.gradle. I run tests using `gradle test`. I would like to be able to do `gradle updatechromedriver test` and not have to do additional runtime config.

**Comment by amirkibbar** [comment]
@leontebbens I think it's reasonable that the plugin will set the webdriver.chrome.driver system property. The question is whether this system property will be available on the test thread, I guess we need to check that

**Comment by leontebbens** [comment]
agree

**Comment by leontebbens** [comment]
another option would be to copy the downloaded chromedriver to the webdriver.chrome.driver location, if it is set

**Comment by leontebbens** [comment]
I'm gonna try that

**Comment by leontebbens** [comment]
works

**Comment by foragerr** [comment]
Great! thanks folks.
