### ISSUE TITLE
Enhancement request: Put downloaded files into a single folder

### ISSUE THREAD

**Issue by foragerr** [leontebbens/chromedriver-updater-plugin#4]
Suggested:

    $buildDir
    |-- Chromedriver
          |-- win
          |-- mac
          |-- linux
          |-- version-info.txt

**Comment by leontebbens** [comment]
Hi, this directory-structure is already generated when you run "gradlew updateChromerdriver". (on my machine MacBook OSX El Captain).
![chromedriver-update-example_output](https://cloud.githubusercontent.com/assets/1188244/17483598/04cee836-5d87-11e6-9e55-1529e53265ee.png)

**Comment by foragerr** [comment]
Your way adds 4 entries under `buildDir`, I'm asking if they can be rolled into a subdirectory under `buildDir`. This is really just preference though, your call.

**Comment by amirkibbar** [comment]
@leontebbens I agree with @foragerr and think it's better to bundle all the artifacts the plugin downloads under a single directory in the build directory instead of under 4 entries with rather generic names. If you agree, I can do it

**Comment by leontebbens** [comment]
I agree with @forragerr; @amirkibbar I assume you want to ditch the win/mac/linux dirs? => What structure do you suggest ?

**Comment by amirkibbar** [comment]
@leontebbens I think we should keep the internal win/mac/linux structure, just add the chromedriver/ before them - just like @foragerr suggested

**Comment by leontebbens** [comment]
Added in version 1.4 bij Amir. Thanx!
