### ISSUE TITLE
getLocalVersion() doesn't work (on mac)

### ISSUE THREAD

**Issue by foragerr** [leontebbens/chromedriver-updater-plugin#5]
I'm on mac osX El Capitan. `getLocalVersion()` doesn't seem to work correctly, resulting in download every time I run `updateChromeDriver`

    $ gradle updatechromedriver
	:updateChromedriver
	Downloading Chromedriver 2.23 from http://chromedriver.storage.googleapis.com ...
	Download complete: the latest Chromedriver is available in /Users/rpgeddam/IdeaProjects/selenium-trial/build

	BUILD SUCCESSFUL
	Total time: 59.935 secs

	$ gradle updatechromedriver
	:updateChromedriver
	Downloading Chromedriver 2.23 from http://chromedriver.storage.googleapis.com ...
	Download complete: the latest Chromedriver is available in /Users/rpgeddam/IdeaProjects/selenium-trial/build

	BUILD SUCCESSFUL
	Total time: 1 mins 41.614 secs

**Comment by leontebbens** [comment]
confirmed, version 1.3 introduces this bug. Thanx. I will look into it

**Comment by leontebbens** [comment]
fixed in version 1.4
