### ISSUE TITLE
please release

### ISSUE THREAD

**Issue by amirkibbar** [leontebbens/chromedriver-updater-plugin#9]
Hi @leontebbens,

can you please release version 1.5 - this version includes important contribution from @ecohen11. He opened a pull request (see #8), and I already merged it into the master.

**Comment by leontebbens** [comment]
Hi Amir, thanx again, but I do see a downside to the (merged) pull request: I cannot test all platforms anymore as only the driver for the current platform is downloaded.
Do you perhaps have (some) time to correct this? If not I will do it next week wednesday.

**Comment by amirkibbar** [comment]
this was actually a good thing @ecohen11 has added for two reasons: it shortens the time it takes to download because only the relevant driver is downloaded; and more importantly - there was a bug in the plugin because mac32 stopped being supported by the chrome driver. This was the first driver the plugin attempted to download (on any platform), and this failed, which means that the plugin in version 1.4 doesn't work at all right now. 

@ecohen11 fixed both problems - on mac it will download only the 64 driver, and if a specific platform has a problem other platforms are not affected.

**Comment by leontebbens** [comment]
Speed is a big pro. I'll release 1.5

**Comment by amirkibbar** [comment]
cool, thanks!

**Comment by leontebbens** [comment]
Hi @amirkibbar and @ecohen11 I just released 1.5. Thanx for you contributions!
